[project]
name = "Deepthon-workspace"
version = "0.1.0"
description = "Monorepo for Deepthon and its Experiments"
requires-python = ">=3.10"
dependencies = ["deepthon", "experiments"]

[tool.uv.workspace]
members = ["deepthon_lib", "experiments"]

[tool.uv]
package = false # this tells uv not to try and install the root as a package

[tool.uv.sources]
deepthon = {workspace = true}
experiments = {workspace = true}

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pytest>=9.0.2",
]


[tool.pytest.ini_options]
testpaths = ["tests"]
